Net Core StartUp/MyApplication/Entities/Settings/Menus/ApplicationRoleMenu.cs
using Microsoft.AspNetCore.Identity;
using MyApplication.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyApplication.Entities
{
    public class ApplicationRoleMenu 
    {
        public ApplicationRoleMenu()
        {
            Permissions = new HashSet<MenuPermission>();
        }

        [Key, Column(Order = 1), DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public virtual string Id { get; set; }

        //[Column(Order = 2)]
        //public virtual string RoleId { get; set; }

        //[Column(Order = 3)]
        //public virtual string MenuId { get; set; }
        //[Column(Order = 4)]
        //public virtual string PermissionId { get; set; }

        public virtual string Kd_cabang { get; set; }
        public virtual string Kd_Terminal { get; set; }
        public virtual ApplicationRole Role { get; set; }
        public virtual Permission Permission { get; set; }
        public virtual MenuItem Menu { get; set; }
        public ICollection<MenuPermission> Permissions { get; set; }
    }
}

Net Core StartUp/MyApplication/Entities/Settings/Menus/MenuManager.cs
using Microsoft.EntityFrameworkCore;
using MyApplication.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;

namespace MyApplication.Entities
{

    public class MenuManager
    {
        private readonly ApplicationDbContext _context;

        public MenuManager(ApplicationDbContext context)
        {
            _context = context;
        }

        public ICollection<MenuPermission> GetMenuPermissionsByUser(string user)
        {
            if (user == null)
            {
                return new Collection<MenuPermission>();
            }

            return _context.Roles
                //.Include(role => role.MenuItems.Select(menu => menu.Permissions))
                .Where(role => role.User.UserId == user)
                .SelectMany(role => role.MenuItems.SelectMany(roleMenu => roleMenu.Permissions))
                .ToList();
        }


        public ICollection<MenuItem> GetMenuByUser(string user,
            Func<MenuPermission, bool> filterFunc = null)
        {
            var items = GetMenuPermissionsByUser(user);

            var records = filterFunc == null
                ? items.ToList()
                : items.Where(filterFunc).ToList();

            return records
                .GroupBy(menuPermission => menuPermission.RoleMenu.Menu)
                .Select(grouping => grouping.Key)
                .ToList();
        }

        public ICollection<MenuItem> GetAllByUser(string user)
        {
            return GetMenuByUser(user);
        }

        public IEnumerable<MenuItem> GetViewableMenuItems(string user)
        {
            return GetMenuByUser(user, menuPermission => menuPermission.Permission.Name == "View");
        }

        public ICollection<MenuItem> GetCreateMenuItems(string user)
        {
            return GetMenuByUser(user, menuPermission => menuPermission.Permission.Name == "Create");
        }

        public ICollection<MenuItem> GetDeleteMenuItems(string user)
        {
            return GetMenuByUser(user, menuPermission => menuPermission.Permission.Name == "Delete");
        }

        public ICollection<MenuItem> GetUpdateMenuItems(string user)
        {
            return GetMenuByUser(user, menuPermission => menuPermission.Permission.Name == "Update");
        }

        public ICollection<MenuItem> GetUploadMenuItems(string user)
        {
            return GetMenuByUser(user, menuPermission => menuPermission.Permission.Name == "Upload");
        }

        public ICollection<MenuItem> GetPublishMenuItems(string user)
        {
            return GetMenuByUser(user, menuPermission => menuPermission.Permission.Name == "Publish");
        }

    }
}

Net Core StartUp/MyApplication/Models/Content/ModalFooter.cs
namespace MyApplication.Models
{
    public class ModalFooter
    {
        public string SubmitButtonText { get; set; } = "Save";
        public string EraseButtonText { get; set; } = "Erase";
        public string CancelButtonText { get; set; } = "Cancel";
        public string SubmitButtonID { get; set; } = "btn-submit";
        public string EraseButtonID { get; set; } = "btn-erase";
        public string CancelButtonID { get; set; } = "btn-cancel";
        public bool OnlyCancelButton { get; set; } = false;
        public bool OnlyCancelSaveButton { get; set; } = false;
    }
}

Net Core StartUp/MyApplication/Models/Content/ModalHeader.cs
namespace MyApplication.Models
{
    public class ModalHeader
    {
        public string Heading { get; set; }
    }
}

Net Core StartUp/MyApplication/Models/Settings/Menus/MenuViewModel.cs
using MyApplication.Entities;
using System.Collections.Generic;

namespace MyApplication.Models
{
    public class MenuViewModel
    {
        public ICollection<MenuItem> MenuItems { get; set; }
        public ApplicationUser User { get; set; }
        public IEnumerable<ApplicationRole> Roles { get; set; }
        public ICollection<MenuPermission> Permissions { get; set; }
    }
}

Net Core StartUp/MyApplication/Controllers/Dashboard/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using MyApplication.Entities;
using MyApplication.Security.Authorization;

namespace MyApplication.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            //string userName = userManager.GetUserName(User);
            return View();
        }
        [MyAuthorize("Programmer", "About", AuthPermissions.Read)]
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }
        [MyAuthorize("Programmer", "Contact", AuthPermissions.Read)]
        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }
        [AllowAnonymous]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Net Core StartUp/MyApplication/Controllers/Settings/Menus/MenuController.cs
using MyApplication.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using MyApplication.Entities;
using Microsoft.EntityFrameworkCore;

namespace MyApplication.Controllers
{
    [Authorize]
    [Area("Settings")]
    public class MenuController : Controller
    {
        private ApplicationDbContext _Context;

        public MenuController(ApplicationDbContext context)
        {
            this._Context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<MenuItem> model = new List<MenuItem>();
            model = _Context.Menus.ToList();
            return View(model);
        }
        [HttpGet]
        public IActionResult AddEditMenu(string id)
        {
            MenuItem model = new MenuItem();
            if (!String.IsNullOrEmpty(id))
            {
                MenuItem Menu = _Context.Menus.SingleOrDefault(c => c.Id == id);
                if (Menu != null)
                {
                    model = Menu;
                }
            }
            return PartialView("_AddEditMenu", model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEditMenu(string id, MenuItem model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool isExist = !String.IsNullOrEmpty(id);
                    MenuItem Menu = isExist ? _Context.Menus.Find(id) : new MenuItem { };
                    if (Menu != null)
                    {
                        Menu.Name = model.Name;
                        Menu.Url = model.Url;
                        Menu.ParentId = model.ParentId;
                        Menu.Icon = model.Icon;
                        Menu.Order = model.Order;
                        Menu.Category = model.Category;

                        if (isExist)
                        {
                            Menu.UpdatedBy = User.Identity.Name;
                            Menu.UpdatedDate = DateTime.Now;
                            _Context.Menus.Update(Menu);
                        }
                        else
                        {
                            Menu.CreatedBy = User.Identity.Name;
                            Menu.CreatedDate = DateTime.Now;
                            await _Context.Menus.AddAsync(Menu);
                        }
                    }
                    
                    await _Context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteMenu(string id)
        {
            MenuItem menu = new MenuItem();
            if (!String.IsNullOrEmpty(id))
            {
                MenuItem Menu = await _Context.Menus.FindAsync(id);
                if (Menu != null)
                {
                    menu.Id = id;
                    menu.Name = Menu.Name;
                }
            }
            return PartialView("_DeleteMenu", menu);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteMenu(string id, IFormCollection form)
        {
            try
            {
                if (!String.IsNullOrEmpty(id))
                {
                    MenuItem Menu = await _Context.Menus.FindAsync(id);
                    if (Menu != null)
                    {
                        _Context.Menus.Remove(Menu);
                        await _Context.SaveChangesAsync();
                    }
                }
            } catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Net Core StartUp/MyApplication/Controllers/VesselPlanning/VesselScheduleEstimateController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using DataTables.AspNet.Core;
using DataTables.AspNet.AspNetCore;
using SpinerService;
using System.Security.Claims;

namespace MyApplication.Controllers.VesselPlanning
{

    [Authorize]
    [Area("VesselPlanning")]
    public class VesselScheduleEstimateController : Controller
    {
        private PelindoServiceClient _Service = new PelindoServiceClient();

        // GET: VesselScheduleEstimate
        public ActionResult Index()
        {
            return View();
        }

        // GET: VesselScheduleEstimate/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: VesselScheduleEstimate/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VesselScheduleEstimate/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<StringResponse> Create([FromBody]SaveVesScheduleEstRequest collection)
        {
            StringResponse Response = new StringResponse();

            if (ModelState.IsValid)
            {
                var _CI = User.Identity as ClaimsIdentity;
                Response = await _Service.SaveVesScheduleEstAsync(new SaveVesScheduleEstRequest
                {
                    XKdCabang = _CI.FindFirst("KD_CABANG").Value,
                    XKdTerminal = _CI.FindFirst("KD_TERMINAL").Value,
                    XVesCode = collection.XVesCode,
                    XVesName = collection.XVesName,
                    XAgent = collection.XAgent,
                    XPBM = collection.XPBM,
                    XLOA = collection.XLOA,
                    XKeterangan = collection.XKeterangan,
                    XStatus = "1",
                    XEstArrivalTime = collection.XEstArrivalTime,
                    XEstDepartureTime = collection.XEstDepartureTime,
                    ZKdFrom = collection.ZKdFrom,
                    ZKdTo = collection.ZKdTo,
                    XLastPort = collection.XLastPort,
                    XNextPort = collection.XNextPort,
                    XOriginPort = collection.XOriginPort,
                    XDestPort = collection.XDestPort,
                    XCreatedPort = _CI.FindFirst("USERNAME").Value,
                    XBerthNo = collection.XBerthNo,
                    XGt = collection.XGt,
                    XBendera = collection.XBendera,
                    XPalka = collection.XPalka,
                    XPalkaType = collection.XPalkaType,
                    XLastPortName = collection.XLastPortName,
                    XNextPortName = collection.XNextPortName,
                    XOriginPortName = collection.XOriginPortName,
                    XDestPortName = collection.XDestPortName,
                    XBerthName = collection.XBerthName,
                    XProgramName = _CI.FindFirst("APP_NAME").Value,
                    Validated = new IsValidated
                    {
                        GUID = _CI.FindFirst("GUID").Value,
                        USERNAME = _CI.FindFirst("USERNAME").Value,
                        TOKEN = _CI.FindFirst("TOKEN").Value
                    }
                });

                return Response;
            }
            else
            {
                return new StringResponse { Status = "EV", Result = null, Message = "Your Input data is not Valid. #02" };
            }
        }

        [HttpGet]
        public IActionResult DataVessel()
        {
            return PartialView("_DataVessel");
        }

        // GET: VesselScheduleEstimate/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: VesselScheduleEstimate/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VesselScheduleEstimate/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: VesselScheduleEstimate/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GetDataVessel(IDataTablesRequest request)
        {
            // Nothing important here. Just creates some mock data.
            var _CI = User.Identity as ClaimsIdentity;
            var data = await _Service.GetVesScheduleEstAsync(new GetVesScheduleEstRequest
            {
                KD_CABANG = _CI.FindFirst("KD_CABANG").Value,
                KD_TERMINAL = _CI.FindFirst("KD_TERMINAL").Value,
                Validated = new IsValidated
                {
                    GUID = _CI.FindFirst("GUID").Value,
                    USERNAME = _CI.FindFirst("USERNAME").Value,
                    TOKEN = _CI.FindFirst("TOKEN").Value
                }
            });

            if (data.Status == "S")
            {
                // Global filtering.
                var filteredData = string.IsNullOrEmpty(request.Search.Value) && string.IsNullOrWhiteSpace(request.Search.Value) ? data.Result : data.Result.Where(p =>
                    p.VES_CODE.ToString().ToLower().Contains(request.Search.Value.ToLower()) ||
                    p.VES_NAME.ToString().ToLower().Contains(request.Search.Value.ToLower()) ||
                    p.MPLG_NAMA.ToString().ToLower().Contains(request.Search.Value.ToLower()) ||
                    p.EST_ARRIVAL_TIME.ToString().ToLower().Contains(request.Search.Value.ToLower()) ||
                    p.EST_DEPARTURE_TIME.ToString().ToLower().Contains(request.Search.Value.ToLower()) ||
                    p.LOKASI.ToString().ToLower().Contains(request.Search.Value.ToLower())
                ).ToArray();


                // Paging filtered data.
                var dataPage = filteredData.Skip(request.Start).Take(request.Length);

                var response = DataTablesResponse.Create(request, data.Result.Count(), filteredData.Count(), dataPage);

                return new DataTablesJsonResult(response, true);
            }
            else
            {
                return Json(data);
            }
        }
    }
}

Net Core StartUp/MyApplication/Views/Shared/_Footer.cshtml
<footer class="site-footer">
    <div class="row">
        <div class="col-md-6">
            <p class="text-center text-md-left"><a href="https://www.pelindo.co.id">PT. Pelabuhan IndonesiaIII (Persero)</a></p>
        </div>
        <div class="col-md-6">
            <ul class="nav nav-primary justify-content-center justify-content-md-end">
                <li class="nav-item">
                    <a class="nav-link" href="#">ICT Solution</a>
                </li>
            </ul>
        </div>
    </div>
</footer>

Net Core StartUp/MyApplication/Views/Shared/_Menu.cshtml
<li class="menu-category">MAIN APPLICATION</li>
<li class="menu-item">
    <a asp-area="" asp-controller="Dashboard" asp-action="Index" class="menu-link">
        <span class="icon fa fa-home"></span>
        <span class="title">Dashboard</span>
    </a>
</li>

<li class="menu-item">
    <a class="menu-link" href="#">
        <span class="icon fa fa-compass"></span>
        <span class="title">Vessel Planning</span>
        <span class="arrow"></span>
    </a>
    <ul class="menu-submenu">
        <li class="menu-item">
            <a class="menu-link" asp-area="VesselPlanning" asp-controller="VesselScheduleEstimate" asp-action="Index" >
                <span class="dot"></span>
                <span class="title">Vessel Schedule Estimation</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#" target="_blank">
                <span class="dot"></span>
                <span class="title">Vessel Schedule Plan</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#" target="_blank">
                <span class="dot"></span>
                <span class="title">Relokasi (Non Vessel)</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#" target="_blank">
                <span class="dot"></span>
                <span class="title">Stripping Stuffing</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#" target="_blank">
                <span class="dot"></span>
                <span class="title">Maintenance and Repair</span>
            </a>
        </li>
    </ul>
</li>
<li class="menu-item">
    <a class="menu-link" href="#">
        <span class="icon fa fa-compass"></span>
        <span class="title">Booking service</span>
        <span class="arrow"></span>
    </a>
    <ul class="menu-submenu">
        <li class="menu-item">
            <a class="menu-link" href="#" target="_blank">
                <span class="dot"></span>
                <span class="title">Receiving SS</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#" target="_blank">
                <span class="dot"></span>
                <span class="title">Delivery SS</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#" target="_blank">
                <span class="dot"></span>
                <span class="title">Relokasi (Non Vessel)</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#" target="_blank">
                <span class="dot"></span>
                <span class="title">Stripping Stuffing</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#" target="_blank">
                <span class="dot"></span>
                <span class="title">Maintenance and Repair</span>
            </a>
        </li>
    </ul>
</li>

<li class="menu-item">
    <a class="menu-link" href="#">
        <span class="icon fa fa-car"></span>
        <span class="title">Operasional</span>
        <span class="arrow"></span>
    </a>
    <ul class="menu-submenu">
        <li class="menu-item">
            <a class="menu-link" href="#">
                <span class="dot"></span>
                <span class="title">Receiving & Delivery</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#">
                <span class="dot"></span>
                <span class="title">Relokasi</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#">
                <span class="dot"></span>
                <span class="title">Stripping & Stuffing</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#">
                <span class="dot"></span>
                <span class="title">Maintenance & Repair</span>
            </a>
        </li>
    </ul>
</li>

<li class="menu-item">
    <a class="menu-link" href="#">
        <span class="icon fa fa-television"></span>
        <span class="title">Aktivitas</span>
        <span class="arrow"></span>
    </a>
    <ul class="menu-submenu">
        <li class="menu-item">
            <a class="menu-link" href="#">
                <span class="dot"></span>
                <span class="title">Yard</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#">
                <span class="dot"></span>
                <span class="title">Report</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#">
                <span class="dot"></span>
                <span class="title">Operation</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#">
                <span class="dot"></span>
                <span class="title">Finance</span>
            </a>
        </li>
    </ul>
</li>

<li class="menu-item">
    <a class="menu-link" href="#">
        <span class="icon fa fa-clone"></span>
        <span class="title">EPB</span>
        <span class="arrow"></span>
    </a>
    <ul class="menu-submenu">
        <li class="menu-item">
            <a class="menu-link" href="#">
                <span class="dot"></span>
                <span class="title">Fiost Calculation</span>
            </a>
        </li>
    </ul>
</li>

<li class="menu-item">
    <a class="menu-link" href="#">
        <span class="icon fa fa-history"></span>
        <span class="title">Billing</span>
        <span class="arrow"></span>
    </a>
    <ul class="menu-submenu">
        <li class="menu-item">
            <a class="menu-link" href="#">
                <span class="dot"></span>
                <span class="title">Deposit Payment Entry</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#">
                <span class="dot"></span>
                <span class="title">Package Pre-Invoice</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="#">
                <span class="dot"></span>
                <span class="title">Approval package Pre-Invoice</span>
            </a>
        </li>
    </ul>
</li>

<li class="menu-item">
    <a class="menu-link" href="#">
        <span class="icon fa fa-cog"></span>
        <span class="title">Settings</span>
        <span class="arrow"></span>
    </a>
    <ul class="menu-submenu">
        <li class="menu-item">
            <a asp-area="Settings" asp-controller="Privilege" asp-action="Index" class="menu-link">
                <span class="dot"></span>
                <span class="title">Assigment Privileges</span>
            </a>
        </li>
        <li class="menu-item">
            <a asp-area="Settings" asp-controller="Menu" asp-action="Index" class="menu-link">
                <span class="dot"></span>
                <span class="title">Menu Maintenance</span>
            </a>
        </li>
        <li class="menu-item">
            <a asp-area="Settings" asp-controller="Role" asp-action="Index" class="menu-link">
                <span class="dot"></span>
                <span class="title">Master Roles</span>
            </a>
        </li>
        <li class="menu-item">
            <a asp-area="Settings" asp-controller="Permission" asp-action="Index" class="menu-link">
                <span class="dot"></span>
                <span class="title">Master Permissions</span>
            </a>
        </li>
        <li class="menu-item">
            <a asp-area="Settings" asp-controller="User" asp-action="Index" class="menu-link">
                <span class="dot"></span>
                <span class="title">Users Online</span>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" href="menu-copy.html">
                <span class="dot"></span>
                <span class="title">Copy Menu</span>
            </a>
        </li>
    </ul>
</li>

Net Core StartUp/MyApplication/Views/Shared/_Modal.cshtml
@model MyApplication.Models.BootstrapModel
<!-- Modal -->
<div aria-hidden="true" aria-labelledby="@Model.AreaLabeledId" class="modal modal-center fade" id="@Model.ID" tabindex="-1">
    <div class="modal-dialog  @Model.ModalSizeClass">
        <div class="modal-content">
            
        </div>
    </div>
</div>
<!-- END Modal -->

Net Core StartUp/MyApplication/Views/Shared/_ModalFooter.cshtml
@model MyApplication.Models.ModalFooter

<div class="modal-footer grad-blue">
    <button type="button" id="@Model.CancelButtonID" class="btn btn-bold btn-pure text-white" data-dismiss="modal"><i class="ti-close"></i> @Model.CancelButtonText</button>
    @if (!Model.OnlyCancelButton)
    {
        @if (!Model.OnlyCancelSaveButton)
        {
            <button type="button" id="@Model.EraseButtonID" class="btn btn-bold btn-pure text-white"><i class="ti-eraser"></i> @Model.EraseButtonText</button>
        }
        <button type="submit" class="btn btn-bold btn-pure text-white" id="@Model.SubmitButtonID"><i class="ti-check"></i> @Model.SubmitButtonText</button>
    }
</div>

Net Core StartUp/MyApplication/Views/Shared/_ModalHeader.cshtml
@model MyApplication.Models.ModalHeader

<div class="modal-header">
    <h4 class="modal-title" id="myModalLabel">@*<i class="fa fa-plus-circle" aria-hidden="true"></i>*@ @Model.Heading</h4>
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">&times;</span>
    </button>
</div>