Net Core StartUp/MyApplication/Controllers/Dashboard/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using MyApplication.Entities;
using MyApplication.Security.Authorization;

namespace MyApplication.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            //string userName = userManager.GetUserName(User);
            return View();
        }
        [MyAuthorize("Programmer", "About", AuthPermissions.Read)]
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }
        [MyAuthorize("Programmer", "Contact", AuthPermissions.Read)]
        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }
        [AllowAnonymous]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Net Core StartUp/MyApplication/Controllers/PushNotifcation/PushNotificationController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using WebPush.NetCore;
using MyApplication.Models;

namespace MyApplication.Controllers.PushNotifcation
{
    public class PushNotificationController : Controller
    {
        private static string pushEndpoint;
        private static string p256dh;
        private static string auth;

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Fallback()
        {
            return View();
        }

        public void AddSubscription(Subscription Subscription)
        {

            pushEndpoint = Subscription.endpoint;
            p256dh = Subscription.p256dh;
            auth = Subscription.auth;
        }

        public void TriggerPush()
        {

            var subject = @"mailto:example@example.com";
            var publicKey = @"BGARDFzAbeYjcJIAL-0I5dj9B19W5ge6EGrB9rTFTCYBxvYv52r5j709jLnjKHPvFFsD9AVNAYI8oMR1Fu75SBo";
            var privateKey = @"pX2Jv8Gx5zcpV5692eWl5CpeeFucgWxyiKnXIeQq2wg";

            var subscription = new PushSubscription(pushEndpoint, p256dh, auth);
            var vapidDetails = new VapidDetails(subject, publicKey, privateKey);
            //var gcmAPIKey = @"[your key here]";

            var webPushClient = new WebPushClient();
            try
            {
                webPushClient.SendNotification(subscription, "payload", vapidDetails);
                //webPushClient.SendNotification(subscription, "payload", gcmAPIKey);
            }
            catch (WebPushException exception)
            {
                Console.WriteLine("Http STATUS code" + exception.StatusCode);
            }

        }
    }
}

Net Core StartUp/MyApplication/Views/Dashboard/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Net Core StartUp/MyApplication/Views/Dashboard/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Net Core StartUp/MyApplication/Views/Dashboard/Index.cshtml
@model IEnumerable<MyApplication.Models.MenuItem>
@using MyApplication.Models

@{
    ViewData["Title"] = "Dahsboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header class="header bg-ui-general">
    <div class="header-info">
        <div class="left">
            <h2 class="header-title">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">Dahsboard</li>
                </ol>
            </h2>
        </div>
        <div class="right">
            <i class="fa fa-home fa-3x" aria-hidden="true"></i>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row justify-content-center gap-y">
            @*<div class="col-sm-5">
                <a asp-action="AddEditMenu" class="btn btn-float btn-danger mr-10" data-toggle="modal" data-target="#modal-action"><i class="ti-plus"></i></a>
                Add new menus
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <h5 for="input-normal">Filter</h5>
                    <input type="text" class="form-control form-type-line" id="input-normal" placeholder="Masukan pencarian">
                </div>
            </div>*@
        </div>
    </div>
    <br><br>
</header>
<div class="main-content">
    <div class="row">
        <div class="col-12">
            <p>Demo</p>
            <a id="btnPush" class="btn btn-primary btn-lg" href="#" role="button"></a>
            <a id="btnSendPush" class="btn btn-danger btn-lg" href="#" role="button">Test Push Notification</a>
            <div id="subscriptionContext"> </div>
        </div>
    </div>
    <br>
</div>
<!--/.main-content -->

@section scripts{
    <script>
        'use strict';

        const applicationServerPublicKey  = 'BGARDFzAbeYjcJIAL-0I5dj9B19W5ge6EGrB9rTFTCYBxvYv52r5j709jLnjKHPvFFsD9AVNAYI8oMR1Fu75SBo';
        let isSubscribed = false;
        let swRegistration = null;

        function urlB64ToUint8Array(base64String) {
            const padding = '='.repeat((4 - base64String.length % 4) % 4);
            const base64 = (base64String + padding)
                .replace(/\-/g, '+')
                .replace(/_/g, '/');

            const rawData = window.atob(base64);
            const outputArray = new Uint8Array(rawData.length);

            for (let i = 0; i < rawData.length; ++i) {
                outputArray[i] = rawData.charCodeAt(i);
            }
            return outputArray;
        }

        $(document).ready(function () {

            if ('serviceWorker' in navigator && 'PushManager' in window) {
                (function () {
                    navigator.serviceWorker.register('/sw-core.js?v=6').then(function (registration) {
                        //Registration was successful
                        console.log('ServiceWorker registration successfully with scope: ', registration.scope);
                        //notify("ServiceWorker registration successful");
                        console.log("ServiceWorker registration successfully");

                        swRegistration = registration;
                        initialiseUI();
                    }, function (err) {
                        console.log('ServiceWorker registration failed: ', err);
                        notify("ServiceWorker registration failed");
                    });

                    // Subscribe to receive message from service worker

                })();
            } else {
                notify("Service Worker Not Supported!");
                console.log("Service Worker Not Supported!");
            }

         });

        function initialiseUI() {

            // Set the initial subscription value
            swRegistration.pushManager.getSubscription()
                .then(function (subscription) {
                    isSubscribed = !(subscription === null);

                    if (isSubscribed) {
                        console.log('User IS subscribed.');
                    } else {
                        console.log('User is NOT subscribed.');
                    }

                updateBtn();
            });

            $("#btnPush").click(function () {
                swRegistration.pushManager.getSubscription()
                    .then(function (subscription) {
                        isSubscribed = !(subscription === null);
                    if (isSubscribed) {
                        subscription.unsubscribe().then(function (successful) {
                            updateSubscriptionOnServer(null);
                            isSubscribed = false;
                            updateBtn();
                            console.log("You've successfully unsubscribed");
                            notify("Unsubscription successfully");
                        }).catch(function (e) {
                            console.log("Unsubscription failed");
                        })
                    } else {
                        subscribeUser();
                    }
                });
            });

            $("#btnSendPush").click(function () {

                if (isSubscribed) {
                    var url = '@Url.Action("TriggerPush", "PushNotification")'
                    $.post(url,null, function (data, status) { });
                }

            });
        }

        function updateBtn() {

            if (Notification.permission === 'denied') {
                $("#btnPush").text('Push Messaging Blocked.');
                $("#btnPush").prop("disabled", true);
                $("#btnSendPush").prop("disabled", true);
                updateSubscriptionOnServer(null);
                return;
            }

            if (isSubscribed) {
                $("#btnPush").text("Disable Push Messaging");
                $("#btnSendPush").prop("disabled", false);
            } else {
                $("#btnPush").text("Enable Push Messaging");
                $("#btnSendPush").prop("disabled", true);
            }

           // $("#btnPush").prop("disabled", false);
        }

        function subscribeUser() {
            const applicationServerKey = urlB64ToUint8Array(applicationServerPublicKey);
            swRegistration.pushManager.subscribe({
                //an admission that you will show a notification every time a push is sent
                userVisibleOnly: true,
                applicationServerKey: applicationServerKey
            })
                .then(function (subscription) {
                    console.log('User is subscribed.');
                    notify("You've is subscribed.");

                    updateSubscriptionOnServer(subscription);

                    isSubscribed = true;

                    updateBtn();
                })
                .catch(function (err) {
                    console.log('Failed to subscribe the user: ', err);
                    updateBtn();
                });
        }

        function updateSubscriptionOnServer(subscription) {
            // TODO: Send subscription to application server
            if (subscription) {
                var url = '@Url.Action("AddSubscription", "PushNotification")'

                var subscription = JSON.parse(JSON.stringify(subscription));

                console.log(subscription);

                var subObj = { "endpoint": subscription.endpoint, "p256dh": subscription.keys.p256dh, "auth": subscription.keys.auth }

                console.log(subObj);

                try {
                    $.post(url, subObj, function (data, status) { });
                } catch (err) {
                    console.log(err);
                }

                console.log(JSON.stringify(subscription));
                $("#subscriptionContext").text(JSON.stringify(subscription));
            }
        }

    </script>
}